services:
  frontend:
    build: ./employee
    ports:
      - "5173:5173"
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      -  SPRING_APPLICATION_NAME=JDBCTemplateSpringBoot
      -  SPRING_DATASOURCE_POSTGRES_JDBC_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      -  SPRING_DATASOURCE_POSTGRES_USERNAME=postgres
      -  SPRING_DATASOURCE_POSTGRES_PASSWORD=1234
      -  SPRING_DATASOURCE_POSTGRES_DRIVER_CLASS_NAME=org.postgresql.Driver

      # MySQL Config
      -  SPRING_DATASOURCE_MYSQL_JDBC_URL=jdbc:mysql://host.docker.internal:3306/employee_db
      -  SPRING_DATASOURCE_MYSQL_USERNAME=root
      -  SPRING_DATASOURCE_MYSQL_PASSWORD=0000
      -  SPRING_DATASOURCE_MYSQL_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

    depends_on:
      - postgres
      - mysql 
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    networks:
      - my-network
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=employee_db
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    